### ISSUE TITLE
Implement queries

### ISSUE THREAD

**Issue by eddiekelleypdx** [PSU-CloudData/psu-cloud-data#3]
Queries can most likely be partially implemented to query highway, station, and detector data (excluding DetectorEntry readings) before the DetectorEntry data is added to Datastore.

Once we are able to get DetectorEntry entities in the Datastore, the queries can be completed.

**Comment by eddiekelleypdx** [comment]
DetectorEntry entities can now be imported into the Datastore

**Comment by eddiekelleypdx** [comment]
At this point, getting the queries working is probably the highest priority. The latest commit has a fully working import/mapreduce/mapper workflow...The only thing required now is to get queries working. If anyone is having problems getting the environment setup (data imported, etc.) for the queries setup, holler.

**Comment by eddiekelleypdx** [comment]
I'm working on getting query 1 going correctly

**Comment by eddiekelleypdx** [comment]
Due to the fact that the queries seem to be a PITA, I'm investigating changing the model slightly. Nothing too drastic, but potentially creating a "StationEntry" object that will simply contain the same structure as that of the DetectorEntry object, but with additional aggregated SpeedSums. From what I can see, this can most likely be done in the Mapper jobs (which haven't been run yet, and don't take as long as the MapReduce jobs). Those jobs will most likely re-use the data that was generated by MapReduce earlier today.

**Comment by neilgebhard** [comment]
Sounds good. I apologize for not being much help with these queries. I have been having lots of trouble getting the development environment functioning properly on my laptop for reasons I can't figure out. However, I'll be free at school from 10am-4:40pm. I'm willing to devote all that time to getting these queries working. If you guys are willing, perhaps we can meet up and knock out the rest of these queries together.

**Comment by eddiekelleypdx** [comment]
No worries - I'm trying to get things patched up a bit still...I'm hoping that the majority of the work is done, but we will see. I should be available at the times that you're mentioning - we can play it by ear.

**Comment by emumm** [comment]
I get out of my first final at 10 or so also and have all day to work

**Comment by eddiekelleypdx** [comment]
I'm definitely willing to meet near PSU sometime in the late morning if anyone else is...Any suggestions on a good location to work (maybe near the classroom)?

**Comment by neilgebhard** [comment]
The bottom floor of the engineering building can be a nice spot if there are tables open. Also, there's the computer science lab area close by (suite 88 in the basement of the Fourth Avenue Building).

**Comment by timfreilly** [comment]
I've got space for about four people in my office in the CS office area.
 Wouldn't quite fit 5 though...

Tim

**Comment by eddiekelleypdx** [comment]
I don't mind standing...

**Comment by emumm** [comment]
I just got to the CS department round tables

**Comment by eddiekelleypdx** [comment]
I'm heading down there from Gresham now...Will probably be 45 min. or so. We may be running low on time to get the model changed, and I'm thinking that simply trying to get the queries going with the current model might be most efficient.

**Comment by neilgebhard** [comment]
I'll be over there soon as well.

**Comment by timfreilly** [comment]
Had to drop my wife off at home but I should be back in the CS office in about 20-30. 

Tim

**Comment by Damaniel** [comment]
I'm stuck at work today, but I'll still try to get there as soon as possible (I'll aim to be there by 3).

**Comment by eddiekelleypdx** [comment]
Where are you guys at?

Eddie Kelley
kelleye@pdx.edu

**Comment by timfreilly** [comment]
Shaun, we are in the 115 office area (just around behind the CS main desk).
 We might either be in the lab area just inside 115 or in my office 115-06
by the time you get here.

Tim

**Comment by Damaniel** [comment]
I was just coming to ask this - I'm sneaking out of work right now to come by.  I should be there before 3.
