### ISSUE TITLE
Add CSS styling to user interface

### ISSUE THREAD

**Issue by eddiekelleypdx** [PSU-CloudData/psu-cloud-data#4]
It sure is a bland interface...maybe we can dress it up a bit?

**Comment by Damaniel** [comment]
I've modified the CSS file (and the HTML, slightly, to help with the layout).  Colors are obviously debatable.  I'll push what I've got shortly.

**Comment by eddiekelleypdx** [comment]
That is looking beautiful...

We might be short just one "f" on line 53 of index.html tho (maybe just
amend the commit) ...

I'm going to try to look into an easier way to run the second "Mapper" job
(from the index page?) instead of having to find the key, go to map reduce
page, and run.

**Comment by Damaniel** [comment]
I see you got the fix in.  Stupid text editor error on my part, sorry.

**Comment by Damaniel** [comment]
Now that I've seen it with the tables in place, it looks like it needs a little more work.  I'll adjust the blobstore->datastore table div to use a horizontal scrollbar and change the colors of the cells to make the interiors more readable.
