### ISSUE TITLE
Project progress

### ISSUE THREAD

**Issue by eddiekelleypdx** [PSU-CloudData/psu-cloud-data#7]
It seems like we're getting pretty close with the project. There are still a few things that we need to get implemented:
- Queries 1 may be working - verification will be necessary.
- Queries 2-4 need to be fully implemented
- Decisions on Mapper behavior need to be made (new issue may be created)

If anyone is having issues getting the MapReduce jobs to run in their local development environment, it's possible that that "Sign in as administrator" checkbox needs to be selected after submitting a MR job. Once the app is deployed, it won't be necessary to specify (your Gmail ID authenticates you as an admin automatically)...

**Comment by Damaniel** [comment]
Does your most recent push have the up-to-date query 1?

**Comment by eddiekelleypdx** [comment]
Yeah - the query 1 that's in main.py should be functional (given that the highways, stations, detectors, and an applicable detector entry interval has been imported)

**Comment by eddiekelleypdx** [comment]
I just pushed an additional commit that fixes an exception occurring when highways are None when performing Q1.

**Comment by eddiekelleypdx** [comment]
The latest commit has been deployed to the production server.

Billing has been enabled in the production environment.

The first full MapReduce job (DailySpeedSum) has been started. I'm assuming that this process should take about 2-3 hours from what I had observed in the past. While the job is running, the status can be observed at http://psu-cloud-data.appspot.com/mapreduce/pipeline/status?root=a68bb31582ed4173a63ae327f8ae573a. Make sure to sign in with the Gmail account that is setup as a Developer for the application (not our PDX accounts - thanks OIT).

**Comment by eddiekelleypdx** [comment]
The first couple of attempts at running the DailySpeedSum seemed to get stuck. So far, removing the task retry limitation from queue.yaml seems to be helping. I suspect that some tasks needed to retry and that this setting was causing them to get stuck (fingers crossed). The URL for the current job is http://psu-cloud-data.appspot.com/mapreduce/pipeline/status?root=be746797ff6f4787871cfb2c8c381213

**Comment by eddiekelleypdx** [comment]
MapReduce job for DailySpeedSum finished in about 1hr. 11min!!

Combined with the two failed attempts this AM, the app has used about $0.90 worth of front end instance time and datastore reads (relieving). In the last 4 "real" hours, something like 40 "machine" hours of front end instance time was used by the app. It's interesting to observe the graph showing the shuffle/hash part of the pipeline hitting the cluster at something like 7 requests per second.

I've started the HourlySpeedSum MR job...Hopefully this and the additional jobs can complete processing today.

I attempted to use the Mapper to import the DailySpeedSum blob into the Datastore, but it was not quite working right (it was grabbing the 'short' speed sum blob key). I'll try to figure that out before the second MR job finishes.

**Comment by eddiekelleypdx** [comment]
MR job 2 (hourly) finished in 1hr. 20min...The data looks good for both jobs so far. I am going to kick off the 15min. interval now.

**Comment by eddiekelleypdx** [comment]
All of the MapReduce jobs have completed running on the production servers! Those should be the longest running, most costly operations that we'll need to run. I thought that the Datastore reads/writes would use the most time ($0.16 each), but it turns out that the shuffle/hash pipeline portion of the MR jobs seemed to be the one cranking out the most machine time. The total cost for the 132 instance hours that have been used is only $8.34.

The DailySpeedSum data has been imported into Datastore, but none of the other Intervals. We need to hold off on importing the other DetectorEntry data into Datastore until it's modified to limit what's imported. I'm trying to modify the Mapper so that it will only import 9/22/2011 data for the 5 min. interval.
