### ISSUE TITLE
Mapper behavior

### ISSUE THREAD

**Issue by eddiekelleypdx** [PSU-CloudData/psu-cloud-data#8]
The mapper is currently setup to automatically import all data processed from MR jobs to Datastore. However, part of our 'sparse' storage strategy is to not import data if we can avoid it. For that reason, it's probably wise to only import 5 minute intervals for the date that we will be performing that interval's query for.

Although the Mapper pipeline would be somewhat hardcoded to do a single day, does it make sense to configure it to only pull one day's data in? Although the application wouldn't be flexible enough to import other 5 min. intervals without code modifications, it would work for the project?

**Comment by eddiekelleypdx** [comment]
Thinking about the project presentation in class, I'm re-considering using the code that runs the Mapper pipeline immediately after MapReduce imports the data (vs. running them manually using the UI). This will give us the ability to only import the data that we need (i.e., just one day of 5 minute intervals, which are the largest burden on the Datastore).

**Comment by Damaniel** [comment]
As a general rule, I think that anything that gets the 4 assigned queries running with the smallest amount of work is best, even if we have to hardcode values all over the place.  Writing reusable, general code is nice, but for the project, very purpose-specific code is at least as good.

**Comment by eddiekelleypdx** [comment]
The Mapper pipeline has been removed due to the fact that it would be difficult to demonstrate that portion of the workflow independently during the class presentation (it just seems to blend together with the MapReduce job). By splitting this functionality off, it may also be easier to avoid importing all interval values for larger sets like 5 and 15 min.

All mapper functions are specified in the GUI at this point in time.

NOTE: both MapReduce and Mapper functions now REQUIRE uploaded freeway_loopdata blob filenames to be one of the following (for display in the UI):
freeway_loopdata_short.csv.zip
freeway_loopdata_short_16.csv.zip
freeway_loopdata.csv.zip
freeway_loopdata_16.csv.zip
