### ISSUE TITLE
Presentation outline

### ISSUE THREAD

**Issue by eddiekelleypdx** [PSU-CloudData/psu-cloud-data#9]
We should probably get some kind of basic outline started for the presentation (even if it's not a bunch of slides, having a structure for the presentation might help). Immediate ideas that come to mind:
- Demonstrate file upload to Blobstore (highways, stations, detectors, loop data)
  - Display App Engine console Datastore FileMetadata entity
  - Display App Engine console Blobstore file entity
- Demonstrate file import to Blobstore (highways, stations, detectors)
  - Display HTML user interface highway, station, detector output
  - Display App Engine console Datastore Highway, Station, Detector entities
- Demonstrate MapReduce job for speed sums
  - Show MapReduce pipeline status for job while running
  - Run on smallish dataset
- Demonstrate Mapper job for import of speed sums
  - Show MapReduce status detail for job while running
  - Display App Engine console Datastore DetectorEntry and SpeedSum entities
- Demonstrate Datastore queries
  - Provide demonstration using HTML UI
  - Maybe demo GQL queries using App Engine Console? (may not be enough time)

Any suggestions, additions, and/or criticisms of the above are appreciated.

**Comment by neilgebhard** [comment]
According to the the website, things we should include in the final presentation are:

1) Execute all 4 queries. May truncate data set.
2) Critique your data model and query execution plan. What would you change if you could do the design over?
3) Lessons learned: What did you learn about the system you used (and cloud data management in general) from the project? What would you tell someone who was considering using the system you used for the project?

Even though uploading and preprocessing of the dataset (i.e. MR jobs) were not listed here, they were such a huge part of the project; we should definitely mention them. Also, I noticed that #2 and #3 were not mentioned in your outline, Eddie. Perhaps we can talk about those bullet points at the end of the presentation?

**Comment by eddiekelleypdx** [comment]
Yeah - touching on the query plan and design would definitely be beneficial. We probably need to get the queries fully worked out first...

We can probably mention the fact that storing all of the data in its native file form, and aggregating results that we want from that seems to be the most efficient use of the platform; that storing all data on the platform's DB seemed to be horribly inefficient as lessons learned.
